blank_issues_enabled: false
contact_links:
    - name: GitHub Discussions
      url: https://github.com/prismicio-community/php-kit/discussions/new/choose
      about: Ask a question about the package or raise an issue directly related the the package.
